site_name: "ArcTgz"
description: "A next‑generation archive format built with Rust. Super robust, cross‑platform, and designed for speed and safety."
language: "en"
base_url: "https://mroczect.github.io/arctgz"
author: "mroczect"
repo_url: "https://github.com/mroczect/arctgz.git"
license: "MIT"

navbar:
  - label: "Home"
    url: "index.html"
  - label: "Installation"
    url: "installation.html"
  - label: "Usage"
    url: "usage.html"
  - label: "Configuration"
    url: "configuration.html"
  - label: "API Reference"
    url: "api-reference.html"
  - label: "Cargo Docs"
    url: "cargo-doc/"
  - label: "License"
    url: "license.html"

sidebar:
  - label: "Home"
    url: "index.html"
  - label: "Installation"
    url: "installation.html"
  - label: "Usage"
    url: "usage.html"
  - label: "Configuration"
    url: "configuration.html"
  - label: "API Reference"
    url: "api-reference.html"
  - label: "Cargo Docs"
    url: "cargo-doc/"
  - label: "License"
    url: "license.html"
